### ISSUE TITLE
script generating same-size backup every time

### ISSUE THREAD

**Issue by ominds** [pedroetb/rsync-incremental-backup#18]
Hello,

I'm backing up to a remote location (SSH). Every backup is the same size as the original data folder. So it would seem the script is doing a full backup? Is this the normal behavior? I expected that each backup.X folder would be much smaller than the initial data folder.

**Comment by pedroetb** [comment]
Hi, maybe your target file system doesn't support symbolic links?

**Comment by ominds** [comment]
Src and destination are Linux. So that's not the issue.

Can I somehow tell rsync to do crc rather than timestamp checks? 

I'm guessing that timestamp checks are always wrong and so all files are sent over everytime? 

How can I enable crc checks?

**Comment by jezek** [comment]
@pedroetb  I think the script creates hard links instead of symbolic links.

@ominds How do you check the directory sizes? Sometimes direcories with hard links can be [confuzing](https://stackoverflow.com/questions/19951883/du-counting-hardlinks-towards-filesize). For me the backup works as expected. 

Here are some listings in backup dir:
```bash
$ du -hsl *
11G	backup.1
11G	backup.2
11G	backup.3
11G	backup.4
11G	backup.5
11G	backup.6
7,9G	backup.7
3,4M	log

$ du -hs *
11G	backup.1
105M	backup.2
87M	backup.3
50M	backup.4
80M	backup.5
46M	backup.6
70M	backup.7
3,4M	log
```
As you can see, each dir has cca 11GB individualy, but when not counting hard links more than once the sizes are smaller.

**Comment by ominds** [comment]
I think this has to do with how I take the backup. I take an lvm snapshot of the running system, then mount it in a directory, then do the backup from it, then unmount and delete the snapshot. Maybe everytime I take a new snapshot and mount and do a backup, there are time differences? That's my best guess.

That's why I thought I'd better change to crc instead. But this is all guess work honestly.

**Comment by pedroetb** [comment]
@ominds ok, but in Linux you can also use filesystems without linking support (they create copies of the files instead). As you said, the time attribute could be the problem.

You can set `-c` or `--checksum` parameter to rsync command to check changes using sizes and checksums instead of times. At the moment, you should modify the script to include this change, but I'm planning to allow user passing rsync parameters through the script.

@jezek you are right, I meant to say hard links, sorry!

In issue #11 there are some examples for testing the script, it might be useful to you.

**Comment by ominds** [comment]
This is really confusing. I added --checksum (on line 132), still, look

```
[root@host db]# du -hs data
20G	data
[root@host db]# cd backup/
[root@host backup]# ls
backup.1  backup.2  log
[root@host backup]# du -hs backup.1
20G	backup.1
[root@host backup]# du -hs backup.2
20G	backup.2
```

I took these in sequence. Is this normal?

**Comment by jezek** [comment]
@ominds What do you get, when you run ```du -hd1 .``` in the ```backup``` directory?

**Comment by ominds** [comment]
```
20G	./backup.2
6.1G	./backup.1
14M	./log

```

Ok, I'm a bit confused here. I've always used du -hs, any explanation appreciated!

**Comment by Dateranoth** [comment]
@ominds Theres a really good explanation here:
https://stackoverflow.com/questions/19951883/du-counting-hardlinks-towards-filesize

**Comment by pedroetb** [comment]
@ominds ok, problem solved :smile: You need to measure disk usage on parent directory, not individually (using `-h -s` or `-h -d 1`, doesn't matter).

Thanks @jezek @Dateranoth !!
