### ISSUE TITLE
backup directory size

### ISSUE THREAD

**Issue by Gouldile** [pedroetb/rsync-incremental-backup#27]
Hello

Thank you very much for this script, sorry if my english is not good.

if I understood the script copy the "data" folder in backup.1, backup.1 in backup.2 etc... so that if we have a large file in "data" it is found in all the "backup" folders.

Do you know how to do so that in the "backup" folders there are only the files/folders modified ? 

TY

**Comment by pedroetb** [comment]
Hi! The script doesn't copy files from `data` to `backup` directories, only keep references to them if not changed or add new content if it is modified (incremental backup).

When a file is not changed during successive backups, the script will keep the original file only in the oldest `backup` directory (the one with bigger number suffix), but it will be accessible from newer `backup` and `data` directories because of hardlinks usage (references to same original file).

You will find more info at project README and at this external reference: <https://www.admin-magazine.com/Articles/Using-rsync-for-Backups>.

**Comment by Gouldile** [comment]
Thank you very much for those explanations :)
