### ISSUE TITLE
Backup Error: Broken Pipe

### ISSUE THREAD

**Issue by achmet9948** [pedroetb/rsync-incremental-backup#7]
Hello everyone, 
I have at the moment following problem: I start the script and its look fine. After a few minutes stop the script, it looks like it hangs on one file and following error is comming: 
rsync: [sender] write rror: Broken pipe (32)
rsync error: unexplaned error (code 255) at io.c (829) [sender=3.1.2]
[DATE] Backup failed, try again later

I tried to copy many files (round about tenthousend) from my server via vpn to my raspberry. 
If I start the script only with an sql-dump file, it works fine.
Have you some Idea?

What I did already: 
- delete all files at the target 
- restart target server
- restart source server

**Comment by pedroetb** [comment]
Hi, the broken pipe error is normal when you stop the execution. The hang on that file, may be caused by the size of that particular file. How long you wait before stopping the script?
Also, check if you are using compression (`-z` flag) or checksum comparison (`-c` flag), because it can slow down the process due to a bigger CPU demand.
